#! /bin/sh

xrandr --output HDMI-0 --mode 2560x1080 --rate 75 &
xset -dpms s off
change_brightness
xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &
wmname compiz
picom &

polybar main &
feh --bg-scale $HOME/Immagini/Wallpapers/34.jpg &
bspc monitor -d Main Opt Media Games

bspc config focused_border_color "#FFFFFF"
bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Productivity
bspc rule -a Gcolor3     state=floating
# Media
bspc rule -a Gnome-music desktop='^3' follow=on
bspc rule -a org.gnome.Music desktop='^3' follow=on
bspc rule -a vlc         desktop='^3' follow=on
bspc rule -a Totem       desktop='^3' follow=on
# Games
bspc rule -a yuzu        desktop='^4' follow=on state=floating
bspc rule -a Ryujinx        desktop='^4' follow=on state=floating
bspc rule -a Steam       desktop='^4' follow=on state=floating
bspc rule -a Bottles     desktop='^4' follow=on state=floating
# Others
bspc rule -a Kupfer.py   focus=on
bspc rule -a Screenkey   manage=off
